### ISSUE TITLE
Deploy kibana

### ISSUE THREAD

**Issue by gpelouze** [QCDIS/KMS-generic-helm-charts#20]
Kibana is available in the elk Helm chart, but has no authentication if `elasticsearch.security.enable` is set to `false`.

**Comment by gpelouze** [comment]
Resources:
- https://github.com/bitnami/charts/tree/main/bitnami/elasticsearch/README.md
- https://github.com/bitnami/charts/blob/main/bitnami/kibana/README.md
- https://github.com/bitnami/charts/issues/13093
- https://github.com/bitnami/charts/issues/10076

```yaml
elasticsearch:
  security:
    enabled: true
    elasticPassword: "%!@#"
    tls:
      restEncryption: false
      autoGenerated: true

  global:
    kibanaEnabled: true

  kibana:
    elasticsearch:
      security:
        auth:
          enabled: true
          createSystemUser: true
          kibanaPassword: "#!%@"
          elasticsearchPasswordSecret: kms-elasticsearch
        tls:
          enabled: false
          autoGenerated: false
```

Then, login with elastic user (kibana_system is to talk with eslasticsearch).
